#!/usr/bin/env node
/**
 * PreToolUse hook on Edit|MultiEdit|Write. Two jobs, both at the moment the
 * edit happens, because a CLAUDE.md sentence read an hour ago loses to
 * whatever else is in context (plan mode's "Explore only" phase did exactly
 * that):
 *
 *   1. Generated-file guard (BLOCKS). A file carrying the agent-os banner was
 *      compiled from `.agent-os/`; the next `sync` reverts any edit to it.
 *      Deny, and name the source to edit instead.
 *   2. Cartographer reminder (advisory, never blocks). The first edit to an
 *      existing feature with no cartographer map adds a note telling Claude to
 *      ask agent-os:feature-cartographer first. Once per feature per session.
 *
 * Stays silent for new (untracked) features, paths outside a feature
 * directory, and anything it cannot work out. Turn the reminder off with
 * `{ "claude": { "cartographerReminder": false } }` in `.agent-os/config.json`.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, isAbsolute, join, relative } from "node:path";
import { claudeConfig, featureOf, findMap, mapFiles, tracked } from "../lib/features.mjs";

// Must stay a substring of BANNER in src/source.mjs.
const BANNER = "agent-os: generated from .agent-os/";

const quiet = () => process.exit(0);
const emit = (hookSpecificOutput) => {
  process.stdout.write(JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", ...hookSpecificOutput } }));
  process.exit(0);
};

let payload;
try { payload = JSON.parse(readFileSync(0, "utf8") || "{}"); } catch { quiet(); }

const root = process.env.CLAUDE_PROJECT_DIR || payload?.cwd || process.cwd();
const raw = String(payload?.tool_input?.file_path ?? "");
if (!raw) quiet();
const abs = isAbsolute(raw) ? raw : join(root, raw);
const rel = relative(root, abs).replace(/\\/g, "/");
if (rel.startsWith("..")) quiet();

// ---- 1. generated-file guard
try {
  if (existsSync(join(root, ".agent-os")) && existsSync(abs) && readFileSync(abs, "utf8").includes(BANNER)) {
    let source = ".agent-os/";
    const rule = rel.match(/^\.(?:claude|clinerules|cursor|windsurf|kilocode|gemini|agents?)\/(?:rules\/)?(.+?)\.(?:md|mdc)$/);
    if (rel === "AGENTS.md") source = ".agent-os/AGENTS.md";
    else if (rule && existsSync(join(root, ".agent-os/rules", `${basename(rule[1])}.md`)))
      source = `.agent-os/rules/${basename(rule[1])}.md`;
    emit({
      permissionDecision: "deny",
      permissionDecisionReason:
        `${rel} is generated by agent-os and the next sync would revert this edit. ` +
        `Make the change in ${source} instead, then run \`npx @sayansr26/agent-os sync\`.`,
    });
  }
} catch { /* fall through to the reminder */ }

// ---- 2. cartographer reminder
try {
  if (claudeConfig(root).cartographerReminder === false) quiet();
  const feature = featureOf(root, rel);
  if (!feature) quiet();
  if (findMap(feature, mapFiles(root))) quiet();
  if (!tracked(root, feature.dir)) quiet();

  const dir = join(tmpdir(), "agent-os-reminders");
  mkdirSync(dir, { recursive: true });
  const session = String(payload?.session_id ?? "nosession").replace(/[^\w-]/g, "");
  const marker = join(dir, `${session}--${feature.dir.replace(/[^\w-]/g, "_")}`);
  if (existsSync(marker)) quiet();
  writeFileSync(marker, "");

  emit({
    additionalContext:
      `agent-os (advisory): ${feature.dir}/ is an existing feature with no cartographer map. ` +
      `Before changing it further, ask agent-os:feature-cartographer how "${feature.name}" is built — ` +
      `it answers and files the map for every later session. This applies in plan mode too ` +
      `(ask it read-only; it writes the map after plan mode ends). Shown once per feature per session.`,
  });
} catch { quiet(); }
quiet();
